import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

import '@/styles/globals.scss';
import Header from '@/components/Header';

const openSans = Open_Sans({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-open-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Nebula Questionnaire',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isGradientTheme = false;
  return (
    <html lang="en" data-theme={isGradientTheme ? 'gradient' : 'default'}>
      <body className={` ${openSans.variable}`}>
        <Header isGradientTheme={isGradientTheme} />
        {children}
      </body>
    </html>
  );
}
